const API_URL='https://script.google.com/macros/s/AKfycbxtffspuIEkJKnGCHBpFbLwNdp6zIoEsp8pvB3nXBosAoz03IvjItDvC50D6cK08TEb/exec';
const form=document.querySelector('#adminForm');
const message=document.querySelector('#message');
const last=document.querySelector('#lastRegistration');
const leaderboardBody=document.querySelector('#leaderboardBody');
const leaderboardMessage=document.querySelector('#leaderboardMessage');
async function send(payload){const response=await fetch(API_URL,{method:'POST',mode:'cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});if(!response.ok)throw Error('El servidor no respondió correctamente.');const data=await response.json();if(!data.ok)throw Error(data.error||'No se pudo completar la operación.');return data;}
function renderLeaderboard(rows){leaderboardBody.innerHTML=rows.length?rows.map((row,index)=>`<tr><td class="rank-number">${index+1}</td><td>${escapeHtml(row.name)}</td><td>${row.visits}</td></tr>`).join(''):'<tr><td colspan="3">Aún no hay visitas registradas.</td></tr>';}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));}
async function loadLeaderboard(adminKey){if(!adminKey){leaderboardMessage.textContent='Ingresa la clave de administradora para consultar la tabla.';return;}leaderboardMessage.textContent='Actualizando posiciones...';try{const data=await send({action:'leaderboard',adminKey});renderLeaderboard(data.positions||[]);leaderboardMessage.textContent='Tabla actualizada.';}catch(error){leaderboardMessage.textContent=error.message;}}
form.addEventListener('submit',async(event)=>{event.preventDefault();const values=new FormData(form),adminKey=String(values.get('adminKey')).trim(),name=String(values.get('clientName')).trim(),folio=String(values.get('clientFolio')).trim().toUpperCase(),ticket=String(values.get('ticket')).trim(),partner=String(values.get('partner')).trim();if(!adminKey){message.textContent='La clave de administradora es obligatoria.';return;}message.textContent='Validando y guardando visita...';try{const data=await send({action:'register_visit',adminKey,personal:partner,idCliente:folio,ticket,cliente:name,compra:'Visita registrada',fechaServicio:new Date().toISOString()});message.textContent=`Visita registrada correctamente. Ticket: ${data.ticket}.`;last.textContent=`${name} · Ticket ${ticket} · Socia: ${partner}`;await loadLeaderboard(adminKey);form.reset();}catch(error){message.textContent=`No se pudo registrar: ${error.message}`;}});
document.querySelector('#refreshLeaderboard').addEventListener('click',()=>loadLeaderboard(String(document.querySelector('#adminKey').value).trim()));