const SPREADSHEET_ID='1CXyRAaQXF1YWW0ZkQttnLmN2hPbRKyPJ-47oFXP98h0';
const VISITS_SHEET='Hoja 1'; const CLIENTS_SHEET='CLIENTAS'; const MAX_NAME=100; const MAX_PHONE=20; const MAX_TICKET=60;

function doGet(e){e=e||{parameter:{}};const p=e.parameter||{};const action=String(p.action||'health');let result=action==='client'?getClient_(String(p.folio||'')):({ok:true,service:'Bicha Studios',version:'secure-v2'});return respond_(result,String(p.callback||''));}
function doPost(e){const lock=LockService.getScriptLock();try{lock.waitLock(10000);const body=JSON.parse((e&&e.postData&&e.postData.contents)||'{}');if(body.action==='register_client')return json_(registerClient_(body));if(body.action==='register_visit')return json_(registerVisit_(body));throw new Error('Acción no válida.');}catch(error){return json_({ok:false,error:safeError_(error)});}finally{try{lock.releaseLock();}catch(_) {}}}
function registerClient_(body){const name=clean_(body.name,MAX_NAME);const phone=normalizePhone_(body.phone);if(name.length<3||phone.length<10)throw new Error('Nombre o teléfono inválido.');const sheet=getClientsSheet_();const rows=sheet.getDataRange().getDisplayValues();const existing=rows.slice(1).find(r=>normalizePhone_(r[2])===phone);if(existing)return {ok:true,existing:true,folio:existing[0],name:existing[1]};const folio=createFolio_(rows);sheet.appendRow([folio,name,phone,new Date(),'ACTIVA']);return {ok:true,existing:false,folio,name};}
function registerVisit_(body){verifyAdmin_(body.adminKey);const folio=clean_(body.idCliente,20).toUpperCase();const ticket=clean_(body.ticket,MAX_TICKET);const client=findClient_(folio);if(!client)throw new Error('La clienta no está registrada.');if(!ticket)throw new Error('El ticket es obligatorio.');const sheet=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(VISITS_SHEET);const rows=sheet.getDataRange().getDisplayValues();if(rows.slice(1).some(r=>String(r[2]).trim().toLowerCase()===ticket.toLowerCase()))throw new Error('El ticket ya está registrado.');sheet.appendRow([clean_(body.personal,80),clean_(body.adminKey,120),ticket,client.name,folio,new Date(),clean_(body.compra,80)||'Visita registrada',String(body.fechaServicio||new Date().toISOString())]);return {ok:true,ticket,folio};}
function getClient_(folio){folio=clean_(folio,20).toUpperCase();if(!/^[A-Z0-9-]{4,20}$/.test(folio))return {ok:false,found:false};const client=findClient_(folio);if(!client)return {ok:true,found:false};const sheet=SpreadsheetApp.openById(SPREADSHEET_ID).getSheetByName(VISITS_SHEET);const visits=sheet.getDataRange().getDisplayValues().slice(1).filter(r=>String(r[4]).trim().toUpperCase()===folio).length;return {ok:true,found:true,folio,name:client.name,visits};}
function verifyAdmin_(key){const expected=PropertiesService.getScriptProperties().getProperty('ADMIN_KEY_HASH');if(!expected||sha256_(String(key||''))!==expected)throw new Error('Administradora no autorizada.');}
function sha256_(value){return Utilities.base64Encode(Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,value,Utilities.Charset.UTF_8));}
function normalizePhone_(value){return String(value||'').replace(/\D/g,'').slice(0,MAX_PHONE);}
function clean_(value,max){return String(value||'').replace(/[<>]/g,'').trim().slice(0,max);}
function getClientsSheet_(){const ss=SpreadsheetApp.openById(SPREADSHEET_ID);let sheet=ss.getSheetByName(CLIENTS_SHEET);if(!sheet){sheet=ss.insertSheet(CLIENTS_SHEET);sheet.appendRow(['FOLIO','NOMBRE','TELEFONO','FECHA DE ALTA','ESTADO']);}return sheet;}
function findClient_(folio){const rows=getClientsSheet_().getDataRange().getDisplayValues();const row=rows.slice(1).find(r=>String(r[0]).trim().toUpperCase()===folio);return row?{folio:row[0],name:row[1],phone:row[2]}:null;}
function createFolio_(rows){let folio;do{folio='BS-'+Utilities.getUuid().replace(/-/g,'').slice(0,8).toUpperCase();}while(rows.some(r=>r[0]===folio));return folio;}
function respond_(payload,callback){const body=JSON.stringify(payload);if(/^[A-Za-z_$][\w$]*$/.test(callback))return ContentService.createTextOutput(callback+'('+body+');').setMimeType(ContentService.MimeType.JAVASCRIPT);return ContentService.createTextOutput(body).setMimeType(ContentService.MimeType.JSON);}
function json_(payload){return ContentService.createTextOutput(JSON.stringify(payload)).setMimeType(ContentService.MimeType.JSON);}
function safeError_(error){return String(error&&error.message||'Error interno').slice(0,180);}
