const API_URL='https://script.google.com/macros/s/AKfycbxo5714fCDqTJJzeQsbRzD8C79-AlCKNc5msIlRc4Xz6EXk1kRp3HmDpejZuST-t1_-/exec';
const PUBLIC_BASE_URL='https://tarjeta.communet.info'; const form=document.querySelector('#clientForm'); const success=document.querySelector('#success'); const message=document.querySelector('#formMessage');
function normalizePhone(value){return value.replace(/\D/g,'');}
function getClients(){return JSON.parse(localStorage.getItem('bicha-clientes')||'{}');}
function saveClients(clients){localStorage.setItem('bicha-clientes',JSON.stringify(clients));}
function showCard(client){const cardUrl=`${PUBLIC_BASE_URL}/index.html?folio=${encodeURIComponent(client.folio)}`;const qrUrl=`https://api.qrserver.com/v1/create-qr-code/?size=500x500&margin=12&data=${encodeURIComponent(cardUrl)}`;document.querySelector('#folio').textContent=client.folio;document.querySelector('#qrImage').src=qrUrl;document.querySelector('#cardLink').href=cardUrl;form.closest('.signup-card').classList.add('is-success');form.hidden=true;success.hidden=false;}
async function registerClient(payload){const response=await fetch(API_URL,{method:'POST',mode:'cors',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify(payload)});if(!response.ok)throw new Error('El servidor no respondió correctamente.');const data=await response.json();if(!data.ok)throw new Error(data.error||'No se pudo registrar la clienta.');return data;}
form.addEventListener('submit',async(event)=>{event.preventDefault();const values=new FormData(form);const name=String(values.get('name')).trim();const phone=String(values.get('phone')).trim();if(normalizePhone(phone).length<10){message.textContent='Captura un teléfono válido de al menos 10 dígitos.';message.style.color='#a74568';return;}message.textContent='Guardando registro...';message.style.color='#684a56';try{const data=await registerClient({action:'register_client',name,phone});const client={folio:data.folio,name:data.name||name,phone,visits:[]};const clients=getClients();clients[client.folio]=client;saveClients(clients);localStorage.setItem('bicha-demo-card',JSON.stringify(client));showCard(client);message.textContent=data.existing?'La clienta ya estaba registrada. Se mostró su tarjeta existente.':'Registro creado correctamente.';message.style.color='#55784d';}catch(error){message.textContent=`No se pudo completar el registro: ${error.message}`;message.style.color='#a74568';}});
document.querySelector('#newClient').addEventListener('click',()=>{form.reset();form.hidden=false;success.hidden=true;form.closest('.signup-card').classList.remove('is-success');message.textContent='';});
